import type {
  ActivityLog,
  ContactMethod,
  ContactStatus,
  DashboardBrief,
  NextStep,
  Person,
  Priority,
  ResearchOrganization,
  ResearchPoolState,
  ResearchStatus,
  WorkUpdate,
} from "./research-pool-types";

export const RESEARCH_STATUSES: ResearchStatus[] = [
  "待调研",
  "待联系",
  "已联系",
  "已回复",
  "已预约",
  "已访谈",
  "跟进中",
  "已结束",
  "长期维护",
  "暂停推进",
];

export const PRIORITIES: Priority[] = [
  "S",
  "A",
  "B",
  "C",
];

export const CONTACT_STATUSES: ContactStatus[] = [
  "暂不联系",
  "待批准联系",
  "计划联系",
  "已联系",
  "已回复",
  "已约访谈",
  "已完成访谈",
  "待跟进",
  "潜在合作线索",
  "已关闭",
];

export const ROLE_OPTIONS = [
  "Professor",
  "Principal Investigator",
  "Research Professor",
  "Postdoc",
  "PhD Student",
  "Master Student",
  "Research Scientist",
  "Industry Researcher",
] as const;

export const FLAG_OPTIONS = [
  "重点关注",
  "信息待核验",
  "近期联系",
  "需要上级判断",
  "潜在合作对象",
  "暂不推进",
] as const;

export const DEFAULT_RESEARCH_TOPICS = [
  "Embodied AI",
  "Vision-Language-Action",
  "Robot Manipulation",
  "Robot Learning",
  "Multi-Robot Systems",
  "Human-Robot Interaction",
  "Autonomous Navigation",
  "Sim-to-Real",
  "Soft Robotics",
  "Surgical Robotics",
  "Embodied Evaluation",
  "Formal Methods",
  "Robot Planning",
  "Real-world Data",
  "Benchmark",
] as const;

export const DEFAULT_TAGS = [
  "VLA",
  "Multi-Robot",
  "Manipulation",
  "Real-world Data",
  "Benchmark Author",
  "BU",
  "MIT Connection",
  "Industry Connection",
] as const;

const today = "2026-07-17";
const initialCreatedAt = "2026-06-28";
const initialVerifiedAt = "2026-07-08";

const source = (title: string, url = "https://www.bu.edu/") => ({
  title,
  url,
  sourceType: "seed",
  accessedAt: today,
});

const contact = (
  type: ContactMethod["type"],
  value: string,
  label: string = type,
): ContactMethod => ({
  id: `contact-${type}-${value}`.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
  type,
  label,
  value,
});

function buildResearchDocument(person: Person) {
  const sections = [
    ["简介", person.bio],
    ["当前研究重点", person.currentResearchFocus],
    ["研究方向", [...person.researchTopics, ...person.secondaryTopics].join("; ")],
    ["代表项目", person.representativeProjects.join("; ")],
    [
      "数据集 / 评测基准 / 机器人平台",
      [...person.datasets, ...person.benchmarks, ...person.robotPlatforms].join("; "),
    ],
    ["研究类型", person.researchMode],
    ["为什么值得关注", person.whyImportant],
    ["与 ZODA 的相关性", person.zodaRelevance],
    ["潜在数据需求", person.potentialDataNeed],
    ["评测基准价值", person.benchmarkValue],
    ["网络连接价值", person.networkValue],
    ["推荐接触方式", person.recommendedApproach],
    ["建议访谈问题", person.interviewQuestions],
  ];

  return sections
    .filter(([, value]) => value)
    .map(([label, value]) => `## ${label}\n${value}`)
    .join("\n\n");
}

function normalizePriority(value = ""): Priority {
  const trimmed = value.trim().toUpperCase();
  if (trimmed === "S" || /核心|高优先|高$/.test(value)) {
    return "S";
  }
  if (trimmed === "A" || /中高/.test(value)) {
    return "A";
  }
  if (trimmed === "B" || /中低|中/.test(value)) {
    return "B";
  }
  if (trimmed === "C" || /低|暂不|未评估/.test(value)) {
    return "C";
  }
  return "C";
}

const basePerson = (overrides: Partial<Person> & Pick<Person, "id" | "name">): Person => {
  const person: Person = {
    degree: "",
    avatarUrl: "",
    role: "PhD Student",
    title: "研究人员",
    institution: "Boston University",
    lab: "Collaborative Autonomy Group",
    department: "Engineering",
    location: "Boston, Massachusetts",
    bio: "具身智能科研对象池的种子记录。",
    currentResearchFocus: "需要在详细调研阶段进一步核验。",
    contacts: [contact("主页", "https://www.bu.edu/", "公开主页待核验")],
    feishuDocUrl: "",
    shortAssessment: "",
    supervisorNote: "",
    managerNote: "先补齐公开资料和联系人判断。",
    researchDocument: "",
    researchTopics: ["Embodied AI"],
    secondaryTopics: [],
    representativeProjects: [],
    representativePublications: [],
    datasets: [],
    benchmarks: [],
    robotPlatforms: [],
    researchMode: "仿真 + 真实机器人",
    whyImportant: "BU 优先调研阶段的种子对象。",
    zodaRelevance: "可能与具身数据、机器人评测基准或访谈调研相关。",
    potentialDataNeed: "未评估。",
    benchmarkValue: "未评估。",
    networkValue: "有助于扩展科研对象池。",
    recommendedApproach: "联系前先核验公开资料。",
    interviewQuestions:
      "下一步应该重点梳理哪些真实机器人数据、评测基准、合作者和实验室连接？",
    researchStatus: "待调研",
    priority: "未评估",
    contactStatus: "暂不联系",
    owner: "Eric",
    isStarred: false,
    flags: ["信息待核验"],
    tags: ["BU"],
    nextAction: "核验主页、实验室成员身份和代表成果。",
    followUpDate: "2026-07-30",
    advisorIds: [],
    adviseeIds: [],
    collaboratorIds: [],
    formerAffiliations: [],
    sources: [source("BU seed list")],
    archived: false,
    lastModifiedBy: "Eric",
    lastModifiedAt: "2026-07-16 15:00",
    lastVerifiedAt: initialVerifiedAt,
    createdAt: initialCreatedAt,
    updatedAt: today,
    ...overrides,
  };

  return {
    ...person,
    priority: normalizePriority(person.priority),
    isStarred: normalizePriority(person.priority) === "S" && person.isStarred,
    shortAssessment:
      overrides.shortAssessment ??
      (person.shortAssessment.includes("待补充") ? "" : person.shortAssessment),
    supervisorNote:
      overrides.supervisorNote ?? person.supervisorNote ?? person.managerNote ?? "",
    feishuDocUrl:
      overrides.feishuDocUrl ?? `https://example.feishu.cn/docx/${person.id}`,
    researchDocument: overrides.researchDocument ?? buildResearchDocument(person),
  };
};

export const seedPeople: Person[] = [
  basePerson({
    id: "alyssa-pierson",
    name: "Alyssa Pierson",
    degree: "PhD",
    role: "Professor",
    title: "Associate Professor",
    lab: "Collaborative Autonomy Group",
    department: "Mechanical Engineering",
    bio: "研究方向包括协作自主、多机器人系统、机器人规划和人机交互。",
    currentResearchFocus:
      "面向人机约束的协作自主和多机器人决策。",
    researchTopics: ["Multi-Robot Systems", "Human-Robot Interaction", "Robot Planning"],
    secondaryTopics: ["Embodied AI", "Autonomous Navigation"],
    representativeProjects: ["Collaborative autonomy research mapping seed"],
    representativePublications: [
      {
        title: "Representative multi-robot autonomy publication",
        year: "TBD",
        venue: "TBD",
        url: "",
        summary: "待补充核验后的代表性成果。",
      },
    ],
    robotPlatforms: ["Mobile robots", "Multi-robot systems"],
    whyImportant:
      "BU 多机器人自主和人机协作方向的重要种子对象。",
    priority: "高",
    researchStatus: "待联系",
    contactStatus: "待批准联系",
    isStarred: true,
    flags: ["重点关注", "需要上级判断", "近期联系"],
    tags: ["BU", "Multi-Robot", "Real-world Data"],
    nextAction: "请上级判断是否批准进入初步联系。",
    managerNote: "优先确认是否批准联系，并核验真实机器人数据或多机器人 benchmark。",
    followUpDate: "2026-07-20",
    createdAt: "2026-07-15",
    lastVerifiedAt: "2026-07-15",
    adviseeIds: ["akua-dickson", "sabbir-ahmad"],
    collaboratorIds: ["roberto-tron"],
  }),
  basePerson({
    id: "eshed-ohn-bar",
    name: "Eshed Ohn-Bar",
    degree: "PhD",
    role: "Principal Investigator",
    title: "Assistant Professor",
    lab: "H2X Lab",
    department: "Electrical and Computer Engineering",
    bio: "研究方向包括具身感知、人本自主系统和学习系统。",
    currentResearchFocus:
      "人本具身 AI、多模态感知和面向自主系统的学习方法。",
    researchTopics: ["Embodied AI", "Vision-Language-Action", "Robot Learning"],
    secondaryTopics: ["Human-Robot Interaction", "Autonomous Navigation"],
    robotPlatforms: ["Autonomous systems"],
    whyImportant: "与具身智能和 Physical AI 定位高度相关。",
    priority: "高",
    researchStatus: "已访谈",
    contactStatus: "计划联系",
    isStarred: true,
    flags: ["重点关注", "信息待核验"],
    tags: ["BU", "VLA", "Real-world Data"],
    nextAction: "补充实验室主页、当前学生和代表项目。",
    createdAt: "2026-07-14",
    lastVerifiedAt: "2026-07-15",
    advisorIds: [],
    adviseeIds: ["kamran-vakil"],
  }),
  basePerson({
    id: "andrew-sabelhaus",
    name: "Andrew Sabelhaus",
    degree: "PhD",
    role: "Principal Investigator",
    title: "Assistant Professor",
    lab: "Soft Robotics Control Lab",
    department: "Mechanical Engineering",
    bio: "研究方向包括软体机器人、控制和物理具身机器人系统。",
    currentResearchFocus: "软体机器人系统的控制方法和物理设计。",
    researchTopics: ["Soft Robotics", "Control Systems", "Robot Manipulation"],
    secondaryTopics: ["Sim-to-Real", "Robot Learning"],
    robotPlatforms: ["Soft robots"],
    researchMode: "Real-world",
    whyImportant: "对软体机器人和控制导向的 Physical AI 方向有价值。",
    priority: "高",
    researchStatus: "跟进中",
    contactStatus: "暂不联系",
    flags: ["潜在合作对象"],
    tags: ["BU", "Manipulation"],
    lastVerifiedAt: "2026-07-14",
    adviseeIds: ["brennan-brodt"],
    collaboratorIds: ["tommaso-ranzani"],
  }),
  basePerson({
    id: "wenchao-li",
    name: "Wenchao Li",
    degree: "PhD",
    role: "Professor",
    title: "Associate Professor",
    lab: "RASTIC",
    department: "Electrical and Computer Engineering",
    bio: "研究方向包括可信自主系统、形式化方法和智能系统安全。",
    currentResearchFocus:
      "面向可信自主与机器人系统的形式化方法和评测。",
    researchTopics: ["Formal Methods", "Embodied Evaluation", "Autonomous Navigation"],
    secondaryTopics: ["Robot Planning", "Sim-to-Real"],
    researchMode: "仿真",
    whyImportant: "与安全、验证和具身评测高度相关。",
    priority: "高",
    researchStatus: "待调研",
    contactStatus: "暂不联系",
    flags: ["需要上级判断"],
    tags: ["BU", "Benchmark Author"],
    nextAction: "请上级判断是否继续作为高核验对象。",
    managerNote: "形式化方法和具身评测相关，建议先确认优先级再决定是否联系。",
    lastVerifiedAt: "2026-07-12",
    adviseeIds: ["meredith-anderson"],
  }),
  basePerson({
    id: "roberto-tron",
    name: "Roberto Tron",
    degree: "PhD",
    role: "Professor",
    title: "Associate Professor",
    lab: "Collaborative Autonomy Group",
    department: "Mechanical Engineering",
    bio: "研究方向包括机器人、控制、几何方法和分布式自主系统。",
    currentResearchFocus: "分布式机器人系统、控制和几何方法。",
    researchTopics: ["Multi-Robot Systems", "Control Systems", "Robot Planning"],
    secondaryTopics: ["Autonomous Navigation"],
    whyImportant: "有助于连接机器人理论、控制和自主系统方向。",
    priority: "中",
    researchStatus: "待调研",
    contactStatus: "暂不联系",
    flags: ["信息待核验"],
    tags: ["BU", "Multi-Robot"],
    collaboratorIds: ["alyssa-pierson"],
  }),
  basePerson({
    id: "sheila-russo",
    name: "Sheila Russo",
    degree: "PhD",
    role: "Professor",
    title: "Associate Professor",
    lab: "Material Robotics Laboratory",
    department: "Mechanical Engineering",
    bio: "研究方向包括医疗机器人、软体机器人和材料驱动机器人。",
    currentResearchFocus: "医疗机器人和软体机器人机构。",
    researchTopics: ["Surgical Robotics", "Soft Robotics", "Robot Manipulation"],
    secondaryTopics: ["Human-Robot Interaction"],
    researchMode: "真实机器人",
    whyImportant: "对手术机器人和材料机器人方向有价值。",
    priority: "中",
    researchStatus: "待调研",
    contactStatus: "暂不联系",
    flags: ["潜在合作对象"],
    tags: ["BU", "Manipulation"],
  }),
  basePerson({
    id: "tommaso-ranzani",
    name: "Tommaso Ranzani",
    degree: "PhD",
    role: "Professor",
    title: "Associate Professor",
    lab: "Material Robotics Laboratory",
    department: "Mechanical Engineering",
    bio: "研究方向包括软体机器人、仿生系统和机器人操作。",
    currentResearchFocus: "软体与仿生机器人系统。",
    researchTopics: ["Soft Robotics", "Robot Manipulation", "Surgical Robotics"],
    secondaryTopics: ["Sim-to-Real"],
    researchMode: "真实机器人",
    priority: "中",
    researchStatus: "待调研",
    contactStatus: "暂不联系",
    flags: ["信息待核验"],
    tags: ["BU", "Manipulation"],
    collaboratorIds: ["andrew-sabelhaus", "sheila-russo"],
  }),
  basePerson({
    id: "akua-dickson",
    name: "Akua Dickson",
    role: "PhD Student",
    title: "PhD Student",
    lab: "Collaborative Autonomy Group",
    department: "Mechanical Engineering",
    researchTopics: ["Multi-Robot Systems", "Human-Robot Interaction"],
    secondaryTopics: ["Robot Planning"],
    priority: "中",
    researchStatus: "待调研",
    contactStatus: "暂不联系",
    tags: ["BU", "Multi-Robot"],
    advisorIds: ["alyssa-pierson"],
  }),
  basePerson({
    id: "sabbir-ahmad",
    name: "Sabbir Ahmad",
    role: "PhD Student",
    title: "PhD Student",
    lab: "Collaborative Autonomy Group",
    department: "Mechanical Engineering",
    researchTopics: ["Robot Planning", "Multi-Robot Systems"],
    priority: "未评估",
    researchStatus: "待调研",
    contactStatus: "暂不联系",
    tags: ["BU", "Multi-Robot"],
    advisorIds: ["alyssa-pierson"],
  }),
  basePerson({
    id: "kamran-vakil",
    name: "Kamran Vakil",
    role: "PhD Student",
    title: "PhD Student",
    lab: "H2X Lab",
    department: "Electrical and Computer Engineering",
    researchTopics: ["Embodied AI", "Robot Learning"],
    secondaryTopics: ["Vision-Language-Action"],
    priority: "高",
    researchStatus: "跟进中",
    contactStatus: "计划联系",
    flags: ["近期联系"],
    tags: ["BU", "VLA"],
    advisorIds: ["eshed-ohn-bar"],
    createdAt: "2026-07-15",
  }),
  basePerson({
    id: "brennan-brodt",
    name: "Brennan Brodt",
    role: "PhD Student",
    title: "PhD Student",
    lab: "Soft Robotics Control Lab",
    department: "Mechanical Engineering",
    researchTopics: ["Soft Robotics", "Control Systems"],
    priority: "低",
    researchStatus: "待调研",
    contactStatus: "暂不联系",
    tags: ["BU"],
    advisorIds: ["andrew-sabelhaus"],
    managerNote: "请补充他的具体项目和是否有公开机器人平台。",
    createdAt: "2026-07-16",
  }),
  basePerson({
    id: "meredith-anderson",
    name: "Meredith Anderson",
    role: "PhD Student",
    title: "PhD Student",
    lab: "RASTIC",
    department: "Electrical and Computer Engineering",
    researchTopics: ["Formal Methods", "Embodied Evaluation"],
    priority: "未评估",
    researchStatus: "待调研",
    contactStatus: "暂不联系",
    tags: ["BU", "Benchmark Author"],
    advisorIds: ["wenchao-li"],
  }),
];

export const seedActivities: ActivityLog[] = [
  {
    id: "activity-1",
    actor: "Eric",
    actorRole: "Admin",
    action: "新增人员",
    targetType: "person",
    targetId: "alyssa-pierson",
    summary: "Eric 新增了 Alyssa Pierson，并标记为高。",
    createdAt: "2026-07-16 15:00",
  },
  {
    id: "activity-2",
    actor: "Supervisor",
    actorRole: "Editor",
    action: "更新管理备注",
    targetType: "person",
    targetId: "alyssa-pierson",
    summary: "上级要求优先确认 Alyssa Pierson 团队的真实机器人数据或多机器人 benchmark。",
    createdAt: "2026-07-16 15:12",
  },
  {
    id: "activity-3",
    actor: "Eric",
    actorRole: "Admin",
    action: "更新状态",
    targetType: "person",
    targetId: "kamran-vakil",
    summary: "Eric 将 Kamran Vakil 调整为高和计划联系。",
    createdAt: "2026-07-16 15:20",
  },
  {
    id: "activity-4",
    actor: "Supervisor",
    actorRole: "Editor",
    action: "更新管理备注",
    targetType: "person",
    targetId: "brennan-brodt",
    summary: "上级要求补充 Brennan Brodt 的项目和机器人平台信息。",
    createdAt: "2026-07-16 15:25",
  },
];

export const seedUpdates: WorkUpdate[] = [
  {
    id: "update-20260717-1",
    updateType: "新增研究判断",
    title: "确认 BU 多机器人方向优先看 Alyssa Pierson",
    summary: "整理 Collaborative Autonomy Group 的研究方向后，认为其与多机器人自主、人机协作和真实机器人数据需求有直接关系。",
    insight: "建议作为第一批高优先级对象保留，下一步重点看是否有可复用 benchmark 或多机器人实验数据。",
    linkedPersonId: "alyssa-pierson",
    linkedPerson: "Alyssa Pierson",
    linkedOrganization: "Collaborative Autonomy Group",
    feishuUrl: "https://example.feishu.cn/docx/alyssa-pierson",
    author: "Eric",
    occurredAt: "2026-07-17 10:20",
    createdAt: "2026-07-17 10:20",
    updatedAt: "2026-07-17 10:20",
  },
  {
    id: "update-20260717-2",
    updateType: "新增资料",
    title: "补充 H2X Lab 人物资料入口",
    summary: "将 Eshed Ohn-Bar 和 Kamran Vakil 相关资料统一挂到飞书人物文档，便于后续继续补项目和学生关系。",
    insight: "H2X Lab 与具身感知和 VLA 方向相关度高，建议继续补齐代表项目。",
    linkedPersonId: "eshed-ohn-bar",
    linkedPerson: "Eshed Ohn-Bar",
    linkedOrganization: "H2X Lab",
    feishuUrl: "https://example.feishu.cn/docx/eshed-ohn-bar",
    author: "Eric",
    occurredAt: "2026-07-17 11:05",
    createdAt: "2026-07-17 11:05",
    updatedAt: "2026-07-17 11:05",
  },
  {
    id: "update-20260716-1",
    updateType: "新增人员",
    title: "新增 BU 软体机器人方向人员",
    summary: "录入 Andrew Sabelhaus，并关联 Soft Robotics Control Lab 作为后续 Physical AI 对象池的一部分。",
    insight: "该方向更偏真实机器人系统和控制，可作为具身硬件侧补充样本。",
    linkedPersonId: "andrew-sabelhaus",
    linkedPerson: "Andrew Sabelhaus",
    linkedOrganization: "Soft Robotics Control Lab",
    feishuUrl: "https://example.feishu.cn/docx/andrew-sabelhaus",
    author: "Eric",
    occurredAt: "2026-07-16 16:10",
    createdAt: "2026-07-16 16:10",
    updatedAt: "2026-07-16 16:10",
  },
  {
    id: "update-20260716-2",
    updateType: "新增实验室",
    title: "新增 RASTIC 实验室线索",
    summary: "将 Wenchao Li 的 RASTIC 纳入列表，作为可信自主系统和具身评测相关的实验室线索。",
    insight: "形式化方法本身不是机器人主线，但对具身评测、安全验证有补充价值。",
    linkedPersonId: "wenchao-li",
    linkedPerson: "Wenchao Li",
    linkedOrganization: "RASTIC",
    feishuUrl: "https://example.feishu.cn/docx/wenchao-li",
    author: "Eric",
    occurredAt: "2026-07-16 15:35",
    createdAt: "2026-07-16 15:35",
    updatedAt: "2026-07-16 15:35",
  },
  {
    id: "update-20260715-1",
    updateType: "完成信息核验",
    title: "核验 BU H2X Lab 公开信息",
    summary: "核验实验室主页、人员身份和研究方向描述，确认其适合作为具身智能感知方向观察对象。",
    insight: "先不急于联系，继续补代表项目和数据来源。",
    linkedPersonId: "eshed-ohn-bar",
    linkedPerson: "Eshed Ohn-Bar",
    linkedOrganization: "H2X Lab",
    feishuUrl: "https://example.feishu.cn/docx/eshed-ohn-bar",
    author: "Eric",
    occurredAt: "2026-07-15 18:00",
    createdAt: "2026-07-15 18:00",
    updatedAt: "2026-07-15 18:00",
  },
  {
    id: "update-20260714-1",
    updateType: "完成人物调研",
    title: "完成 Andrew Sabelhaus 初步人物调研",
    summary: "整理其软体机器人控制方向、实验室定位和可关联学生线索。",
    insight: "适合作为 Physical AI 硬件/控制侧样本，不作为第一批联系对象。",
    linkedPersonId: "andrew-sabelhaus",
    linkedPerson: "Andrew Sabelhaus",
    linkedOrganization: "Soft Robotics Control Lab",
    feishuUrl: "https://example.feishu.cn/docx/andrew-sabelhaus",
    author: "Eric",
    occurredAt: "2026-07-14 17:15",
    createdAt: "2026-07-14 17:15",
    updatedAt: "2026-07-14 17:15",
  },
];

export const seedDashboardBrief: DashboardBrief = {
  title: "BU 具身智能科研对象池建设",
  description:
    "正在梳理 BU 相关教授、博士、硕士和实验室，重点关注 VLA、多机器人、机器人操作和真实机器人数据。",
  focusAreas: ["VLA", "多机器人", "机器人操作", "真实机器人数据"],
  updatedAt: "2026-07-17 11:05",
  updatedBy: "Eric",
};

export const seedNextSteps: NextStep[] = [
  {
    id: "next-step-1",
    content: "补齐高优先级人员的飞书人物资料和公开来源。",
    completed: false,
    sortOrder: 1,
    createdAt: "2026-07-17 11:05",
    updatedAt: "2026-07-17 11:05",
  },
  {
    id: "next-step-2",
    content: "继续整理 BU 博士生和博后名单，优先看 VLA 与真实机器人数据。",
    completed: false,
    sortOrder: 2,
    createdAt: "2026-07-17 11:05",
    updatedAt: "2026-07-17 11:05",
  },
  {
    id: "next-step-3",
    content: "把有明确判断的新增记录沉淀为上级可快速阅读的日报。",
    completed: false,
    sortOrder: 3,
    createdAt: "2026-07-17 11:05",
    updatedAt: "2026-07-17 11:05",
  },
];

export const seedOrganizations: ResearchOrganization[] = [
  {
    id: "h2x-lab",
    name: "H2X Lab",
    type: "实验室",
    websiteUrl: "",
    note: "BU 具身感知、VLA、自动驾驶评测和真实环境泛化方向的重点实验室线索。当前重点关联 Eshed Ohn-Bar、Kamran Vakil 及 H2X 学生网络。",
    sourceCount: 0,
    createdAt: "2026-07-17 11:05",
    updatedAt: "2026-07-17 11:05",
  },
  {
    id: "collaborative-autonomy-group",
    name: "Collaborative Autonomy Group",
    type: "实验室",
    websiteUrl: "",
    note: "Alyssa Pierson 领导的多机器人协作、自主规划、人机协作和异构机器人团队研究线索。适合作为多机器人 Benchmark 与产业连接的重点组织。",
    sourceCount: 0,
    createdAt: "2026-07-17 11:05",
    updatedAt: "2026-07-17 11:05",
  },
];

export const seedResearchPoolState: ResearchPoolState = {
  people: seedPeople,
  organizations: seedOrganizations,
  activities: seedActivities,
  updates: seedUpdates,
  dashboardBrief: seedDashboardBrief,
  nextSteps: seedNextSteps,
};
